---
- name: Add development user
  sudo: yes
  user: name={{ username }} group=sudo

- name: Install packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - git

- name: Add GitHub command line wrapper
  become: yes
  become_user: "{{ username }}"
  script: scripts/install_hub.sh creates=/home/{{ username }}/bin/hub
